// Generated by https://quicktype.io

export interface Personagem {
    name:          string;
    fullname:      string;
    title:         string;
    description:   string;
    rarity:        string;
    element:       string;
    weapontype:    string;
    substat:       string;
    gender:        string;
    body:          string;
    association:   string;
    region:        string;
    affiliation:   string;
    birthdaymmdd:  string;
    birthday:      string;
    constellation: string;
    cv:            Cv;
    costs:         Costs;
    images:        { [key: string]: string };
    url:           URL;
    version:       string;
}

export interface Costs {
    ascend1: Ascend[];
    ascend2: Ascend[];
    ascend3: Ascend[];
    ascend4: Ascend[];
    ascend5: Ascend[];
    ascend6: Ascend[];
}

export interface Ascend {
    name:  string;
    count: number;
    image?: string;
    source: Array<string>
}

export interface Cv {
    english:  string;
    chinese:  string;
    japanese: string;
    korean:   string;
}

export interface URL {
    fandom: string;
}
